spring.application.name=attendance-system
# MySQL ?????
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=@Myc20060825
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver